# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phpbb3AclGroups',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('group_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('auth_option_id', models.IntegerField()),
                ('auth_role_id', models.IntegerField()),
                ('auth_setting', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_acl_groups',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3AclOptions',
            fields=[
                ('auth_option_id', models.IntegerField(serialize=False, primary_key=True)),
                ('auth_option', models.CharField(max_length=50)),
                ('is_global', models.IntegerField()),
                ('is_local', models.IntegerField()),
                ('founder_only', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_acl_options',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3AclRoles',
            fields=[
                ('role_id', models.IntegerField(serialize=False, primary_key=True)),
                ('role_name', models.CharField(max_length=255)),
                ('role_description', models.TextField()),
                ('role_type', models.CharField(max_length=10)),
                ('role_order', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_acl_roles',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3AclRolesData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('role_id', models.IntegerField()),
                ('auth_option_id', models.IntegerField()),
                ('auth_setting', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_acl_roles_data',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3AclUsers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('auth_option_id', models.IntegerField()),
                ('auth_role_id', models.IntegerField()),
                ('auth_setting', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_acl_users',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Attachments',
            fields=[
                ('attach_id', models.IntegerField(serialize=False, primary_key=True)),
                ('post_msg_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('in_message', models.IntegerField()),
                ('poster_id', models.IntegerField()),
                ('is_orphan', models.IntegerField()),
                ('physical_filename', models.CharField(max_length=255)),
                ('real_filename', models.CharField(max_length=255)),
                ('download_count', models.IntegerField()),
                ('attach_comment', models.TextField()),
                ('extension', models.CharField(max_length=100)),
                ('mimetype', models.CharField(max_length=100)),
                ('filesize', models.IntegerField()),
                ('filetime', models.IntegerField()),
                ('thumbnail', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_attachments',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Banlist',
            fields=[
                ('ban_id', models.IntegerField(serialize=False, primary_key=True)),
                ('ban_userid', models.IntegerField()),
                ('ban_ip', models.CharField(max_length=40)),
                ('ban_email', models.CharField(max_length=100)),
                ('ban_start', models.IntegerField()),
                ('ban_end', models.IntegerField()),
                ('ban_exclude', models.IntegerField()),
                ('ban_reason', models.CharField(max_length=255)),
                ('ban_give_reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_banlist',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Bbcodes',
            fields=[
                ('bbcode_id', models.IntegerField(serialize=False, primary_key=True)),
                ('bbcode_tag', models.CharField(max_length=16)),
                ('bbcode_helpline', models.CharField(max_length=255)),
                ('display_on_posting', models.IntegerField()),
                ('bbcode_match', models.TextField()),
                ('bbcode_tpl', models.TextField()),
                ('first_pass_match', models.TextField()),
                ('first_pass_replace', models.TextField()),
                ('second_pass_match', models.TextField()),
                ('second_pass_replace', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_bbcodes',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Bookmarks',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('topic_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_bookmarks',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Bots',
            fields=[
                ('bot_id', models.IntegerField(serialize=False, primary_key=True)),
                ('bot_active', models.IntegerField()),
                ('bot_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('bot_agent', models.CharField(max_length=255)),
                ('bot_ip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_bots',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Config',
            fields=[
                ('config_name', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('config_value', models.CharField(max_length=255)),
                ('is_dynamic', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_config',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Confirm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('confirm_id', models.CharField(max_length=32)),
                ('session_id', models.CharField(max_length=32)),
                ('confirm_type', models.IntegerField()),
                ('code', models.CharField(max_length=8)),
                ('seed', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_confirm',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Disallow',
            fields=[
                ('disallow_id', models.IntegerField(serialize=False, primary_key=True)),
                ('disallow_username', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_disallow',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Drafts',
            fields=[
                ('draft_id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('save_time', models.IntegerField()),
                ('draft_subject', models.CharField(max_length=100)),
                ('draft_message', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_drafts',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ExtensionGroups',
            fields=[
                ('group_id', models.IntegerField(serialize=False, primary_key=True)),
                ('group_name', models.CharField(max_length=255)),
                ('cat_id', models.IntegerField()),
                ('allow_group', models.IntegerField()),
                ('download_mode', models.IntegerField()),
                ('upload_icon', models.CharField(max_length=255)),
                ('max_filesize', models.IntegerField()),
                ('allowed_forums', models.TextField()),
                ('allow_in_pm', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_extension_groups',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Extensions',
            fields=[
                ('extension_id', models.IntegerField(serialize=False, primary_key=True)),
                ('group_id', models.IntegerField()),
                ('extension', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phpbb3_extensions',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Forums',
            fields=[
                ('forum_id', models.IntegerField(serialize=False, primary_key=True)),
                ('parent_id', models.IntegerField()),
                ('left_id', models.IntegerField()),
                ('right_id', models.IntegerField()),
                ('forum_parents', models.TextField()),
                ('forum_name', models.CharField(max_length=255)),
                ('forum_desc', models.TextField()),
                ('forum_desc_bitfield', models.CharField(max_length=255)),
                ('forum_desc_options', models.IntegerField()),
                ('forum_desc_uid', models.CharField(max_length=8)),
                ('forum_link', models.CharField(max_length=255)),
                ('forum_password', models.CharField(max_length=40)),
                ('forum_style', models.IntegerField()),
                ('forum_image', models.CharField(max_length=255)),
                ('forum_rules', models.TextField()),
                ('forum_rules_link', models.CharField(max_length=255)),
                ('forum_rules_bitfield', models.CharField(max_length=255)),
                ('forum_rules_options', models.IntegerField()),
                ('forum_rules_uid', models.CharField(max_length=8)),
                ('forum_topics_per_page', models.IntegerField()),
                ('forum_type', models.IntegerField()),
                ('forum_status', models.IntegerField()),
                ('forum_posts', models.IntegerField()),
                ('forum_topics', models.IntegerField()),
                ('forum_topics_real', models.IntegerField()),
                ('forum_last_post_id', models.IntegerField()),
                ('forum_last_poster_id', models.IntegerField()),
                ('forum_last_post_subject', models.CharField(max_length=100)),
                ('forum_last_post_time', models.IntegerField()),
                ('forum_last_poster_name', models.CharField(max_length=255)),
                ('forum_last_poster_colour', models.CharField(max_length=6)),
                ('forum_flags', models.IntegerField()),
                ('display_on_index', models.IntegerField()),
                ('enable_indexing', models.IntegerField()),
                ('enable_icons', models.IntegerField()),
                ('enable_prune', models.IntegerField()),
                ('prune_next', models.IntegerField()),
                ('prune_days', models.IntegerField()),
                ('prune_viewed', models.IntegerField()),
                ('prune_freq', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_forums',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ForumsAccess',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('forum_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('session_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'phpbb3_forums_access',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ForumsTrack',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('mark_time', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_forums_track',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ForumsWatch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('forum_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('notify_status', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_forums_watch',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3GamesList',
            fields=[
                ('game_id', models.IntegerField(serialize=False, primary_key=True)),
                ('game_title', models.CharField(max_length=100)),
                ('game_image', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'phpbb3_games_list',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3GamesPlayed',
            fields=[
                ('record', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_games_played',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Groups',
            fields=[
                ('group_id', models.IntegerField(serialize=False, primary_key=True)),
                ('group_type', models.IntegerField()),
                ('group_founder_manage', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('group_desc', models.TextField()),
                ('group_desc_bitfield', models.CharField(max_length=255)),
                ('group_desc_options', models.IntegerField()),
                ('group_desc_uid', models.CharField(max_length=8)),
                ('group_display', models.IntegerField()),
                ('group_avatar', models.CharField(max_length=255)),
                ('group_avatar_type', models.IntegerField()),
                ('group_avatar_width', models.IntegerField()),
                ('group_avatar_height', models.IntegerField()),
                ('group_rank', models.IntegerField()),
                ('group_colour', models.CharField(max_length=6)),
                ('group_sig_chars', models.IntegerField()),
                ('group_receive_pm', models.IntegerField()),
                ('group_message_limit', models.IntegerField()),
                ('group_legend', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_groups',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Icons',
            fields=[
                ('icons_id', models.IntegerField(serialize=False, primary_key=True)),
                ('icons_url', models.CharField(max_length=255)),
                ('icons_width', models.IntegerField()),
                ('icons_height', models.IntegerField()),
                ('icons_order', models.IntegerField()),
                ('display_on_posting', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_icons',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Lang',
            fields=[
                ('lang_id', models.IntegerField(serialize=False, primary_key=True)),
                ('lang_iso', models.CharField(max_length=30)),
                ('lang_dir', models.CharField(max_length=30)),
                ('lang_english_name', models.CharField(max_length=100)),
                ('lang_local_name', models.CharField(max_length=255)),
                ('lang_author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_lang',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Log',
            fields=[
                ('log_id', models.IntegerField(serialize=False, primary_key=True)),
                ('log_type', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('reportee_id', models.IntegerField()),
                ('log_ip', models.CharField(max_length=40)),
                ('log_time', models.IntegerField()),
                ('log_operation', models.TextField()),
                ('log_data', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_log',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Medals',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('dynamic', models.IntegerField()),
                ('device', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('nominated', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('description', models.CharField(max_length=256, blank=True)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_medals',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3MedalsAwarded',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('medal_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('awarder_id', models.BigIntegerField()),
                ('awarder_un', models.CharField(max_length=255)),
                ('awarder_color', models.CharField(max_length=6)),
                ('time', models.IntegerField()),
                ('nominated', models.IntegerField()),
                ('nominated_reason', models.TextField()),
                ('points', models.IntegerField()),
                ('bbuid', models.CharField(max_length=255)),
                ('bitfield', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_medals_awarded',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3MedalsCats',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('order_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_medals_cats',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ModeratorCache',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('forum_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('display_on_index', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_moderator_cache',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Modules',
            fields=[
                ('module_id', models.IntegerField(serialize=False, primary_key=True)),
                ('module_enabled', models.IntegerField()),
                ('module_display', models.IntegerField()),
                ('module_basename', models.CharField(max_length=255)),
                ('module_class', models.CharField(max_length=10)),
                ('parent_id', models.IntegerField()),
                ('left_id', models.IntegerField()),
                ('right_id', models.IntegerField()),
                ('module_langname', models.CharField(max_length=255)),
                ('module_mode', models.CharField(max_length=255)),
                ('module_auth', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_modules',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3PollOptions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('poll_option_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('poll_option_text', models.TextField()),
                ('poll_option_total', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_poll_options',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3PollVotes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('topic_id', models.IntegerField()),
                ('poll_option_id', models.IntegerField()),
                ('vote_user_id', models.IntegerField()),
                ('vote_user_ip', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'phpbb3_poll_votes',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Posts',
            fields=[
                ('post_id', models.IntegerField(serialize=False, primary_key=True)),
                ('topic_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('poster_id', models.IntegerField()),
                ('icon_id', models.IntegerField()),
                ('poster_ip', models.CharField(max_length=40)),
                ('post_time', models.IntegerField()),
                ('post_approved', models.IntegerField()),
                ('post_reported', models.IntegerField()),
                ('enable_bbcode', models.IntegerField()),
                ('enable_smilies', models.IntegerField()),
                ('enable_magic_url', models.IntegerField()),
                ('enable_sig', models.IntegerField()),
                ('post_username', models.CharField(max_length=255)),
                ('post_subject', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
                ('post_checksum', models.CharField(max_length=32)),
                ('post_attachment', models.IntegerField()),
                ('bbcode_bitfield', models.CharField(max_length=255)),
                ('bbcode_uid', models.CharField(max_length=8)),
                ('post_postcount', models.IntegerField()),
                ('post_edit_time', models.IntegerField()),
                ('post_edit_reason', models.CharField(max_length=255)),
                ('post_edit_user', models.IntegerField()),
                ('post_edit_count', models.IntegerField()),
                ('post_edit_locked', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_posts',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Privmsgs',
            fields=[
                ('msg_id', models.IntegerField(serialize=False, primary_key=True)),
                ('root_level', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('icon_id', models.IntegerField()),
                ('author_ip', models.CharField(max_length=40)),
                ('message_time', models.IntegerField()),
                ('enable_bbcode', models.IntegerField()),
                ('enable_smilies', models.IntegerField()),
                ('enable_magic_url', models.IntegerField()),
                ('enable_sig', models.IntegerField()),
                ('message_subject', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('message_edit_reason', models.CharField(max_length=255)),
                ('message_edit_user', models.IntegerField()),
                ('message_attachment', models.IntegerField()),
                ('bbcode_bitfield', models.CharField(max_length=255)),
                ('bbcode_uid', models.CharField(max_length=8)),
                ('message_edit_time', models.IntegerField()),
                ('message_edit_count', models.IntegerField()),
                ('to_address', models.TextField()),
                ('bcc_address', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_privmsgs',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3PrivmsgsFolder',
            fields=[
                ('folder_id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('folder_name', models.CharField(max_length=255)),
                ('pm_count', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_privmsgs_folder',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3PrivmsgsRules',
            fields=[
                ('rule_id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('rule_check', models.IntegerField()),
                ('rule_connection', models.IntegerField()),
                ('rule_string', models.CharField(max_length=255)),
                ('rule_user_id', models.IntegerField()),
                ('rule_group_id', models.IntegerField()),
                ('rule_action', models.IntegerField()),
                ('rule_folder_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_privmsgs_rules',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3PrivmsgsTo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('msg_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('pm_deleted', models.IntegerField()),
                ('pm_new', models.IntegerField()),
                ('pm_unread', models.IntegerField()),
                ('pm_replied', models.IntegerField()),
                ('pm_marked', models.IntegerField()),
                ('pm_forwarded', models.IntegerField()),
                ('folder_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_privmsgs_to',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ProfileFields',
            fields=[
                ('field_id', models.IntegerField(serialize=False, primary_key=True)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.IntegerField()),
                ('field_ident', models.CharField(max_length=20)),
                ('field_length', models.CharField(max_length=20)),
                ('field_minlen', models.CharField(max_length=255)),
                ('field_maxlen', models.CharField(max_length=255)),
                ('field_novalue', models.CharField(max_length=255)),
                ('field_default_value', models.CharField(max_length=255)),
                ('field_validation', models.CharField(max_length=20)),
                ('field_required', models.IntegerField()),
                ('field_show_on_reg', models.IntegerField()),
                ('field_hide', models.IntegerField()),
                ('field_no_view', models.IntegerField()),
                ('field_active', models.IntegerField()),
                ('field_order', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_profile_fields',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ProfileFieldsData',
            fields=[
                ('user_id', models.IntegerField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'phpbb3_profile_fields_data',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ProfileFieldsLang',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('field_id', models.IntegerField()),
                ('lang_id', models.IntegerField()),
                ('option_id', models.IntegerField()),
                ('field_type', models.IntegerField()),
                ('lang_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_profile_fields_lang',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ProfileLang',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('field_id', models.IntegerField()),
                ('lang_id', models.IntegerField()),
                ('lang_name', models.CharField(max_length=255)),
                ('lang_explain', models.TextField()),
                ('lang_default_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_profile_lang',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Ranks',
            fields=[
                ('rank_id', models.IntegerField(serialize=False, primary_key=True)),
                ('rank_title', models.CharField(max_length=255)),
                ('rank_min', models.IntegerField()),
                ('rank_special', models.IntegerField()),
                ('rank_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_ranks',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Reports',
            fields=[
                ('report_id', models.IntegerField(serialize=False, primary_key=True)),
                ('reason_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_notify', models.IntegerField()),
                ('report_closed', models.IntegerField()),
                ('report_time', models.IntegerField()),
                ('report_text', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_reports',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3ReportsReasons',
            fields=[
                ('reason_id', models.IntegerField(serialize=False, primary_key=True)),
                ('reason_title', models.CharField(max_length=255)),
                ('reason_description', models.TextField()),
                ('reason_order', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_reports_reasons',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3SearchResults',
            fields=[
                ('search_key', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('search_time', models.IntegerField()),
                ('search_keywords', models.TextField()),
                ('search_authors', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_search_results',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3SearchWordlist',
            fields=[
                ('word_id', models.IntegerField(serialize=False, primary_key=True)),
                ('word_text', models.CharField(unique=True, max_length=255)),
                ('word_common', models.IntegerField()),
                ('word_count', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_search_wordlist',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3SearchWordmatch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('post_id', models.IntegerField()),
                ('word_id', models.IntegerField()),
                ('title_match', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_search_wordmatch',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Sessions',
            fields=[
                ('session_id', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('session_user_id', models.IntegerField()),
                ('session_last_visit', models.IntegerField()),
                ('session_start', models.IntegerField()),
                ('session_time', models.IntegerField()),
                ('session_ip', models.CharField(max_length=40)),
                ('session_browser', models.CharField(max_length=150)),
                ('session_forwarded_for', models.CharField(max_length=255)),
                ('session_page', models.CharField(max_length=255)),
                ('session_viewonline', models.IntegerField()),
                ('session_autologin', models.IntegerField()),
                ('session_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_sessions',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3SessionsKeys',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('key_id', models.CharField(max_length=32)),
                ('user_id', models.IntegerField()),
                ('last_ip', models.CharField(max_length=40)),
                ('last_login', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_sessions_keys',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Sitelist',
            fields=[
                ('site_id', models.IntegerField(serialize=False, primary_key=True)),
                ('site_ip', models.CharField(max_length=40)),
                ('site_hostname', models.CharField(max_length=255)),
                ('ip_exclude', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_sitelist',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Smilies',
            fields=[
                ('smiley_id', models.IntegerField(serialize=False, primary_key=True)),
                ('code', models.CharField(max_length=50)),
                ('emotion', models.CharField(max_length=50)),
                ('smiley_url', models.CharField(max_length=50)),
                ('smiley_width', models.IntegerField()),
                ('smiley_height', models.IntegerField()),
                ('smiley_order', models.IntegerField()),
                ('display_on_posting', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_smilies',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Styles',
            fields=[
                ('style_id', models.IntegerField(serialize=False, primary_key=True)),
                ('style_name', models.CharField(unique=True, max_length=255)),
                ('style_copyright', models.CharField(max_length=255)),
                ('style_active', models.IntegerField()),
                ('template_id', models.IntegerField()),
                ('theme_id', models.IntegerField()),
                ('imageset_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_styles',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3StylesImageset',
            fields=[
                ('imageset_id', models.IntegerField(serialize=False, primary_key=True)),
                ('imageset_name', models.CharField(unique=True, max_length=255)),
                ('imageset_copyright', models.CharField(max_length=255)),
                ('imageset_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phpbb3_styles_imageset',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3StylesImagesetData',
            fields=[
                ('image_id', models.IntegerField(serialize=False, primary_key=True)),
                ('image_name', models.CharField(max_length=200)),
                ('image_filename', models.CharField(max_length=200)),
                ('image_lang', models.CharField(max_length=30)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('imageset_id', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_styles_imageset_data',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3StylesTemplate',
            fields=[
                ('template_id', models.IntegerField(serialize=False, primary_key=True)),
                ('template_name', models.CharField(unique=True, max_length=255)),
                ('template_copyright', models.CharField(max_length=255)),
                ('template_path', models.CharField(max_length=100)),
                ('bbcode_bitfield', models.CharField(max_length=255)),
                ('template_storedb', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_styles_template',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3StylesTemplateData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('template_id', models.IntegerField()),
                ('template_filename', models.CharField(max_length=100)),
                ('template_included', models.TextField()),
                ('template_mtime', models.IntegerField()),
                ('template_data', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_styles_template_data',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3StylesTheme',
            fields=[
                ('theme_id', models.IntegerField(serialize=False, primary_key=True)),
                ('theme_name', models.CharField(unique=True, max_length=255)),
                ('theme_copyright', models.CharField(max_length=255)),
                ('theme_path', models.CharField(max_length=100)),
                ('theme_storedb', models.IntegerField()),
                ('theme_mtime', models.IntegerField()),
                ('theme_data', models.TextField()),
            ],
            options={
                'db_table': 'phpbb3_styles_theme',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Topics',
            fields=[
                ('topic_id', models.IntegerField(serialize=False, primary_key=True)),
                ('forum_id', models.IntegerField()),
                ('icon_id', models.IntegerField()),
                ('topic_attachment', models.IntegerField()),
                ('topic_approved', models.IntegerField()),
                ('topic_reported', models.IntegerField()),
                ('topic_title', models.CharField(max_length=100)),
                ('topic_poster', models.IntegerField()),
                ('topic_time', models.IntegerField()),
                ('topic_time_limit', models.IntegerField()),
                ('topic_views', models.IntegerField()),
                ('topic_replies', models.IntegerField()),
                ('topic_replies_real', models.IntegerField()),
                ('topic_status', models.IntegerField()),
                ('topic_type', models.IntegerField()),
                ('topic_first_post_id', models.IntegerField()),
                ('topic_first_poster_name', models.CharField(max_length=255)),
                ('topic_first_poster_colour', models.CharField(max_length=6)),
                ('topic_last_post_id', models.IntegerField()),
                ('topic_last_poster_id', models.IntegerField()),
                ('topic_last_poster_name', models.CharField(max_length=255)),
                ('topic_last_poster_colour', models.CharField(max_length=6)),
                ('topic_last_post_subject', models.CharField(max_length=100)),
                ('topic_last_post_time', models.IntegerField()),
                ('topic_last_view_time', models.IntegerField()),
                ('topic_moved_id', models.IntegerField()),
                ('topic_bumped', models.IntegerField()),
                ('topic_bumper', models.IntegerField()),
                ('poll_title', models.CharField(max_length=255)),
                ('poll_start', models.IntegerField()),
                ('poll_length', models.IntegerField()),
                ('poll_max_options', models.IntegerField()),
                ('poll_last_vote', models.IntegerField()),
                ('poll_vote_change', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_topics',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3TopicsPosted',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('topic_posted', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_topics_posted',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3TopicsTrack',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('forum_id', models.IntegerField()),
                ('mark_time', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_topics_track',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3TopicsViews',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('topic_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('last_view_time', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_topics_views',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3TopicsWatch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('topic_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('notify_status', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_topics_watch',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3UserGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('group_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('group_leader', models.IntegerField()),
                ('user_pending', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_user_group',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Users',
            fields=[
                ('user_id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_type', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('user_permissions', models.TextField()),
                ('user_perm_from', models.IntegerField()),
                ('user_ip', models.CharField(max_length=40)),
                ('user_regdate', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('username_clean', models.CharField(unique=True, max_length=255)),
                ('user_password', models.CharField(max_length=40)),
                ('user_passchg', models.IntegerField()),
                ('user_pass_convert', models.IntegerField()),
                ('user_email', models.CharField(max_length=100)),
                ('user_email_hash', models.BigIntegerField()),
                ('user_birthday', models.CharField(max_length=10)),
                ('user_lastvisit', models.IntegerField()),
                ('user_lastmark', models.IntegerField()),
                ('user_lastpost_time', models.IntegerField()),
                ('user_lastpage', models.CharField(max_length=200)),
                ('user_last_confirm_key', models.CharField(max_length=10)),
                ('user_last_search', models.IntegerField()),
                ('user_warnings', models.IntegerField()),
                ('user_last_warning', models.IntegerField()),
                ('user_login_attempts', models.IntegerField()),
                ('user_inactive_reason', models.IntegerField()),
                ('user_inactive_time', models.IntegerField()),
                ('user_posts', models.IntegerField()),
                ('user_lang', models.CharField(max_length=30)),
                ('user_timezone', models.DecimalField(max_digits=5, decimal_places=2)),
                ('user_dst', models.IntegerField()),
                ('user_dateformat', models.CharField(max_length=30)),
                ('user_style', models.IntegerField()),
                ('user_rank', models.IntegerField()),
                ('user_colour', models.CharField(max_length=6)),
                ('user_new_privmsg', models.IntegerField()),
                ('user_unread_privmsg', models.IntegerField()),
                ('user_last_privmsg', models.IntegerField()),
                ('user_message_rules', models.IntegerField()),
                ('user_full_folder', models.IntegerField()),
                ('user_emailtime', models.IntegerField()),
                ('user_topic_show_days', models.IntegerField()),
                ('user_topic_sortby_type', models.CharField(max_length=1)),
                ('user_topic_sortby_dir', models.CharField(max_length=1)),
                ('user_post_show_days', models.IntegerField()),
                ('user_post_sortby_type', models.CharField(max_length=1)),
                ('user_post_sortby_dir', models.CharField(max_length=1)),
                ('user_notify', models.IntegerField()),
                ('user_notify_pm', models.IntegerField()),
                ('user_notify_type', models.IntegerField()),
                ('user_allow_pm', models.IntegerField()),
                ('user_allow_viewonline', models.IntegerField()),
                ('user_allow_viewemail', models.IntegerField()),
                ('user_allow_massemail', models.IntegerField()),
                ('user_options', models.IntegerField()),
                ('user_avatar', models.CharField(max_length=255)),
                ('user_avatar_type', models.IntegerField()),
                ('user_avatar_width', models.IntegerField()),
                ('user_avatar_height', models.IntegerField()),
                ('user_sig', models.TextField()),
                ('user_sig_bbcode_uid', models.CharField(max_length=8)),
                ('user_sig_bbcode_bitfield', models.CharField(max_length=255)),
                ('user_from', models.CharField(max_length=100)),
                ('user_icq', models.CharField(max_length=15)),
                ('user_aim', models.CharField(max_length=255)),
                ('user_yim', models.CharField(max_length=255)),
                ('user_msnm', models.CharField(max_length=255)),
                ('user_jabber', models.CharField(max_length=255)),
                ('user_website', models.CharField(max_length=200)),
                ('user_occ', models.TextField()),
                ('user_interests', models.TextField()),
                ('user_actkey', models.CharField(max_length=32)),
                ('user_newpasswd', models.CharField(max_length=40)),
                ('user_form_salt', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'phpbb3_users',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Warnings',
            fields=[
                ('warning_id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('log_id', models.IntegerField()),
                ('warning_time', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_warnings',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Words',
            fields=[
                ('word_id', models.IntegerField(serialize=False, primary_key=True)),
                ('word', models.CharField(max_length=255)),
                ('replacement', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phpbb3_words',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Wwh',
            fields=[
                ('rolling', models.IntegerField(serialize=False, primary_key=True)),
                ('ip', models.CharField(max_length=15)),
                ('id', models.IntegerField()),
                ('viewonline', models.IntegerField()),
                ('last_page', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_wwh',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Phpbb3Zebra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.IntegerField()),
                ('zebra_id', models.IntegerField()),
                ('friend', models.IntegerField()),
                ('foe', models.IntegerField()),
            ],
            options={
                'db_table': 'phpbb3_zebra',
                'managed': False,
            },
            bases=(models.Model,),
        ),
    ]
